// Metadata + registry for deployed decoys.
//
// This is the piece that actually fixes a real problem in the earlier
// Milestone 2 code: `HONEY_PATH_MARKERS` (`"00_"`, `"confidential"`,
// `"passwords"`) matched paths by substring, which is precisely the
// pattern this doc's "Avoiding Detection" section warns against —
// obvious, guessable bait names. Real decoys generated by templates.rs
// deliberately use *ordinary* names, so substring matching against a
// fixed marker list wouldn't even find them. Exact-path lookup against a
// registry of what was actually deployed is the only mechanism that
// still works once the names stop being predictable.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HoneyMetadata {
    pub honey_id: u64,
    pub created_at_ms: u64,
    pub version: u32,
    pub last_refresh_ms: u64,
    /// Tag string from `templates::TemplateKind::tag()` — stored as a
    /// plain string rather than the enum itself so this module doesn't
    /// need to depend on templates.rs (avoids a needless coupling; only
    /// the manager needs to know what a tag maps back to).
    pub template_tag: String,
    pub is_directory: bool,
    /// The real, OS-native filesystem path — deliberately kept alongside
    /// the normalized lookup key rather than reconstructed from it.
    /// Normalization (lowercase, `/` -> `\`) is a one-way canonicalization
    /// for matching purposes only; reconstructing a path from it and
    /// handing that to `std::fs::remove_file` would silently do the wrong
    /// thing on any platform where `\` isn't a real path separator
    /// (Linux/macOS would treat "watched\finance\payroll.xlsx" as a
    /// single literal filename, not a three-level path).
    pub real_path: PathBuf,
}

/// Every decoy the deception engine currently has deployed, keyed by
/// normalized path. Shared (via `monitor::SharedHoneyRegistry`) between
/// the deception manager, which writes to it on deploy/rotate, and the
/// behavioral engine's event-ingest loop, which only ever reads it.
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct HoneyRegistry {
    entries: HashMap<String, HoneyMetadata>,
}

impl HoneyRegistry {
    pub fn new() -> Self {
        HoneyRegistry {
            entries: HashMap::new(),
        }
    }

    pub fn insert(&mut self, path: &Path, metadata: HoneyMetadata) {
        self.entries.insert(normalize(path), metadata);
    }

    pub fn remove(&mut self, path: &Path) -> Option<HoneyMetadata> {
        self.entries.remove(&normalize(path))
    }

    /// True if `path` (a raw string, as it arrives from telemetry events —
    /// see telemetry/event.rs, which carries paths as `String` throughout)
    /// matches a currently-deployed decoy.
    pub fn contains(&self, path: &str) -> bool {
        self.entries.contains_key(&normalize_str(path))
    }

    pub fn get(&self, path: &str) -> Option<&HoneyMetadata> {
        self.entries.get(&normalize_str(path))
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    #[allow(dead_code)] // standard companion to len(); not called yet, kept for API completeness
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    pub fn paths(&self) -> impl Iterator<Item = &String> {
        self.entries.keys()
    }

    pub fn get_by_key(&self, normalized_key: &str) -> Option<&HoneyMetadata> {
        self.entries.get(normalized_key)
    }

    /// Kept for symmetry with `get_by_key` / `remove` — not called
    /// anywhere in this codebase yet (removal always goes through
    /// `HoneyFileManager::remove_one`, which takes a real `Path` so it
    /// can also delete the file, not just the registry entry), but a
    /// reasonable thing for a future caller that already has a
    /// normalized key on hand to want.
    #[allow(dead_code)]
    pub fn remove_by_key(&mut self, normalized_key: &str) -> Option<HoneyMetadata> {
        self.entries.remove(normalized_key)
    }
}

/// Normalizes a path to a stable lookup key: backslash/forward-slash
/// unified and lowercased. Applied identically on both insert and lookup,
/// so it works as a canonical form regardless of which platform generated
/// the path or which platform is now querying it — important since this
/// agent is developed and tested cross-platform (see the top-level
/// README) even though its primary target is Windows.
fn normalize(path: &Path) -> String {
    normalize_str(&path.to_string_lossy())
}

fn normalize_str(path: &str) -> String {
    path.replace('/', "\\").to_lowercase()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_metadata() -> HoneyMetadata {
        HoneyMetadata {
            honey_id: 1,
            created_at_ms: 0,
            version: 1,
            last_refresh_ms: 0,
            template_tag: "payroll_spreadsheet".to_string(),
            is_directory: false,
            real_path: PathBuf::from("C:\\Users\\alice\\Finance\\Payroll.xlsx"),
        }
    }

    #[test]
    fn lookup_is_case_and_separator_insensitive() {
        let mut registry = HoneyRegistry::new();
        registry.insert(Path::new("C:\\Users\\alice\\Finance\\Payroll.xlsx"), sample_metadata());

        assert!(registry.contains("c:/users/alice/finance/payroll.xlsx"));
        assert!(registry.contains("C:\\USERS\\ALICE\\FINANCE\\PAYROLL.XLSX"));
    }

    #[test]
    fn unrelated_path_is_not_a_decoy() {
        let mut registry = HoneyRegistry::new();
        registry.insert(Path::new("C:\\Finance\\Payroll.xlsx"), sample_metadata());

        assert!(!registry.contains("C:\\Finance\\QuarterlyReport.xlsx"));
    }

    #[test]
    fn substring_of_a_real_word_document_no_longer_false_positives() {
        // The old marker-based approach checked whether a path *contained*
        // a string like "confidential" — which would misfire on something
        // like "C:\Projects\confidential_review_process.docx" that was
        // never actually deployed as a decoy. Exact-path lookup doesn't
        // have this problem.
        let registry = HoneyRegistry::new();
        assert!(!registry.contains("C:\\Projects\\confidential_review_process.docx"));
    }
}
